services:
  baywatch:
    image: danielgt/baywatch:1.9.3
    restart: unless-stopped
    volumes:
      - /dev:/dev
      - /run/udev:/run/udev:ro
      - baywatch_data:/app/data
    privileged: true
    ports:
      - "8585:80"
    environment:
      DATABASE_URL: sqlite:////app/data/baywatch.db
      SCAN_INTERVAL_MINUTES: "60"

volumes:
  baywatch_data:
